modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All Rights Reserved unless stated otherwise. Distrubtion permssion is given to FeedTheBeast and CurseForge for use in modpacks"

[[mods]]
modId = "javd"
version = "${version}"
displayName = "Just Another Void Dimension"
authors = "UnRealDinnerbone"
description = "Void Dimensions"
#logoFile = ""

[[dependencies.javd]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.javd]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.javd]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"